[versions]
compose = "1.9.3"
dokka = "2.1.0"
kotlin = "2.2.21"
mavenPublish = "0.34.0"

[plugins]
jetBrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
jetBrains-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
jetBrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetBrains-kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
